namespace AFCS.TOM.Sbme2Server.SBME
{
    static partial class Queries
    {
        private const string _layouts = @"SELECT HOLDERPROFILEID, LAYOUTNAME, LAYOUTFILENAME, LAYOUTFILETYPE, LAYOUTFILE
            FROM CONFOWN.TSCLAYOUT_HOLDERPROFILE 
            INNER JOIN CONFOWN.TSCGRAPHICLAYOUTFILES ON TSCLAYOUT_HOLDERPROFILE.TSCGRAPHICLAYOUTNAME = TSCGRAPHICLAYOUTFILES.LAYOUTNAME
            WHERE TSCLAYOUT_HOLDERPROFILE.HOLDERPROFILEID = :HOLDERPROFILEID";

        private const string _layoutsU =
            @"SELECT HOLDERPROFILEID
            FROM CONFOWN.TSCLAYOUT_HOLDERPROFILE 
            INNER JOIN CONFOWN.TSCGRAPHICLAYOUTFILES ON TSCLAYOUT_HOLDERPROFILE.TSCGRAPHICLAYOUTNAME = TSCGRAPHICLAYOUTFILES.LAYOUTNAME
            WHERE LAYOUTFILETYPE = 'U'
            ORDER BY HOLDERPROFILEID";
    }
}
