namespace AFCS.TOM.Sbme2Server.SBME2
{
    static partial class Queries
    {
        private const string _insertLongTermContractInHistory = @"INSERT INTO LONGTERMCONTRACTSHISTORY 
        (
        MODIFICATIONDATE,
        ISSUINGDATE,
        SALEOPERATORID,
        SALEDEVICEID,
        LASTSERIALNO,
        BLINSERTDATE,
        BLADDEDBY,
        BLREASONCODE,
        BLBURNOPERATORID,
        BLBURNDEVICECLASSID,
        BLBURNDEVICECODE,
        BLBURNDATETIME,
        BLSUSPENDED,
        GLINSERTDATE,
        GLADDEDBY,
        GLREASONCODE,
        GLCONTRACTBITMAP,
        GLRELOADDATETIME,
        GLRELOADSN,
        GLACTOPENDATE,
        GLACTFILENO,
        GLDEVICEOPERATORID,
        GLDEVICECLASSID,
        GLDEVICECODE,
        RECHARGEDONEDEVICEOPERATORID,
        RECHARGEDONEDEVICECLASSID,
        RECHARGEDONEDEVICECODE,
        RECHARGEDONEDATETIME,
        RECHARGEISSUINGDATE,
        RECHARGESALEOPERATORID,
        RECHARGESALEDEVICEID,
        RECHARGESERIALNO
        )
		SELECT SYSDATE, a.ISSUINGDATE, a.SALEOPERATORID, a.SALEDEVICEID, a.LASTSERIALNO,
               a.BLINSERTDATE, a.BLADDEDBY, a.BLREASONCODE, a.BLBURNOPERATORID, a.BLBURNDEVICECLASSID,
               a.BLBURNDEVICECODE, a.BLBURNDATETIME, a.BLSUSPENDED, a.GLINSERTDATE, a.GLADDEDBY,
               a.GLREASONCODE,a.GLCONTRACTBITMAP,a.GLRELOADDATETIME,a.GLRELOADSN, a.GLACTOPENDATE,
               a.GLACTFILENO, a.GLDEVICEOPERATORID, a.GLDEVICECLASSID, a.GLDEVICECODE,
               a.RECHARGEDONEDEVICEOPERATORID, a.RECHARGEDONEDEVICECLASSID, a.RECHARGEDONEDEVICECODE,
               a.RECHARGEDONEDATETIME, a.RECHARGEISSUINGDATE, a.RECHARGESALEOPERATORID, a.RECHARGESALEDEVICEID,
               a.RECHARGESERIALNO 
        FROM LONGTERMCONTRACTS a 
		WHERE a.ISSUINGDATE = :Issuingdate
			AND a.SALEOPERATORID = :Saleoperatorid
			AND a.SALEDEVICEID = :Saledeviceid 
			AND a.LASTSERIALNO BETWEEN :LastSerialNo AND :FirstSerialNo";
    }
}
